name: bus_ticket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  provider: 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
